{
    "jobs": {
        "build": {
            "runs-on": "ubuntu-22.04",
            "steps": [
                {
                    "name": "Setup Java",
                    "run": "echo \"JAVA_HOME=$JAVA_HOME_17_X64\" >> \"$GITHUB_ENV\""
                },
                {
                    "with": {
                        "fetch-depth": "0",
                        "persist-credentials": "false"
                    },
                    "name": "Checkout",
                    "uses": "actions/checkout@v4"
                },
                {
                    "with": {
                        "path": "**/.gradle/loom-cache",
                        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}",
                        "restore-keys": "${{ runner.os }}-gradle-"
                    },
                    "name": "Cache",
                    "uses": "actions/cache/restore@v3"
                },
                {
                    "with": {
                        "cache-read-only": true,
                        "gradle-home-cache-cleanup": true
                    },
                    "name": "Setup Gradle",
                    "uses": "gradle/gradle-build-action@v3"
                },
                {
                    "name": "Build",
                    "run": "./gradlew checkLicenses build",
                    "id": "build",
                    "env": {
                        "BUILD_CACHE_PASSWORD": "${{ secrets.BUILD_CACHE_PASSWORD }}",
                        "BUILD_CACHE_USER": "${{ secrets.BUILD_CACHE_USER }}",
                        "BUILD_CACHE_URL": "${{ secrets.BUILD_CACHE_URL }}",
                        "SNAPSHOT_MAVEN_PASSWORD": "${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}",
                        "SNAPSHOT_MAVEN_USER": "github",
                        "SNAPSHOT_MAVEN_URL": "https://maven.lukebemish.dev/snapshots/"
                    }
                },
                {
                    "name": "Publish",
                    "run": "./gradlew publish",
                    "id": "publish",
                    "env": {
                        "BUILD_CACHE_PASSWORD": "${{ secrets.BUILD_CACHE_PASSWORD }}",
                        "BUILD_CACHE_USER": "${{ secrets.BUILD_CACHE_USER }}",
                        "BUILD_CACHE_URL": "${{ secrets.BUILD_CACHE_URL }}",
                        "SNAPSHOT_MAVEN_PASSWORD": "${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}",
                        "SNAPSHOT_MAVEN_USER": "github",
                        "SNAPSHOT_MAVEN_URL": "https://maven.lukebemish.dev/snapshots/"
                    }
                }
            ]
        }
    },
    "name": "Snapshot",
    "concurrency": "ci-${{ github.ref }}",
    "on": {
        "workflow_dispatch": {
            
        },
        "push": {
            "branches": [
                "1.*"
            ]
        }
    }
}